# -*- coding: utf-8 -*-
"""
This family file was auto-generated by $Id$
Configuration parameters:
  url = http://finalfantasy.wikia.com/wiki/Final_Fantasy_Wiki ffwiki
  name = ffwiki

Please do not commit this to the Git repository!
"""

from pywikibot import family
from pywikibot.tools import deprecated


class Family(family.Family):
    def __init__(self):
        family.Family.__init__(self)
        self.name = 'ffwiki'
        self.langs = {
            'de': 'de.finalfantasy.wikia.com',
            'is': 'is.finalfantasy.wikia.com',
            'ro': 'ro.finalfantasy.wikia.com',
            'it': 'it.finalfantasy.wikia.com',
            'es': 'es.finalfantasy.wikia.com',
            'ru': 'ru.finalfantasy.wikia.com',
            'nl': 'community.wikia.com',
            'ja': 'ja.finalfantasy.wikia.com',
            'vi': 'vi.finalfantasy.wikia.com',
            'pt': 'pt-br.finalfantasy.wikia.com',
            'fi': 'fi.finalfantasy.wikia.com',
            'eo': 'eo.finalfantasy.wikia.com',
            'pt-br': 'pt-br.finalfantasy.wikia.com',
            'fr': 'fr.finalfantasy.wikia.com',
            'pl': 'pl.finalfantasy.wikia.com',
            'en': 'finalfantasy.wikia.com',
            'ar': 'ar.finalfantasy.wikia.com',
            'zh': 'zh.finalfantasy.wikia.com',
        }

    def scriptpath(self, code):
        return {
            'de': '',
            'is': '',
            'ro': '',
            'it': '',
            'es': '',
            'ru': '',
            'nl': '',
            'ja': '',
            'vi': '',
            'pt': '',
            'fi': '',
            'eo': '',
            'pt-br': '',
            'fr': '',
            'pl': '',
            'en': '',
            'ar': '',
            'zh': '',
        }[code]

    @deprecated('APISite.version()')
    def version(self, code):
        return {
            'de': u'1.19.24',
            'is': u'1.19.24',
            'ro': u'1.19.24',
            'it': u'1.19.24',
            'es': u'1.19.24',
            'ru': u'1.19.24',
            'nl': u'1.19.24',
            'ja': u'1.19.24',
            'vi': u'1.19.24',
            'pt': u'1.19.24',
            'fi': u'1.19.24',
            'eo': u'1.19.24',
            'pt-br': u'1.19.24',
            'fr': u'1.19.24',
            'pl': u'1.19.24',
            'en': u'1.19.24',
            'ar': u'1.19.24',
            'zh': u'1.19.24',
        }[code]

    def protocol(self, code):
        return {
            'de': u'http',
            'is': u'http',
            'ro': u'http',
            'it': u'http',
            'es': u'http',
            'ru': u'http',
            'nl': u'http',
            'ja': u'http',
            'vi': u'http',
            'pt': u'http',
            'fi': u'http',
            'eo': u'http',
            'pt-br': u'http',
            'fr': u'http',
            'pl': u'http',
            'en': u'http',
            'ar': u'http',
            'zh': u'http',
        }[code]
